Revert "Update batik library in mpsutil.plantuml"
This reverts commit 1ffe51ab57e1b4e4cf8c3d5d989c68818768a5e8.

It fails with MPS 2018.2 RC1:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.util.SVGLoader$MySVGDOMImplementation
    at com.intellij.util.SVGLoader$MySAXSVGDocumentFactory.<init>(SVGLoader.java:268)
    at com.intellij.util.SVGLoader.<init>(SVGLoader.java:227)
    at com.intellij.util.SVGLoader.load(SVGLoader.java:192)